export const jobs = [
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "8yv3oA_2-UYAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Web Developer - 6-month Contract - Houston Hybrid",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/web-developer-6-month-contract-houston-hybrid-at-dice-3624857671",
    job_description:
      "An established energy client of mine is looking for an experienced Web Developer to join their team on an initial 6-month contract. Starting 6/5, you will be working in an agile team to help develop a new set of web applications for their own system and sub vendors. This role is hybrid and you will be required to go in to the office 3 days p/w. Full-Stack Web Developer 6-month contract (likely extension) Houston - Hybrid working W2 - $70 - $75 p/h C2C - $80 - $90 p/h Starting 06/05 Technical requirements; JavaScript, (React OR Angular OR Vue), Node, HTML, CSSS, API (NO EMPLOYERS OR RECRUTIERS) Oscar Associates Limited (US) is acting as an Employment Business in relation to this vacancy. Web Developer - 6-month Contract - Houston Hybrid",
    job_posted_at_datetime_utc: "2023-06-01T20:56:59.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_offer_expiration_datetime_utc: "2023-07-01T20:56:59.000Z",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_highlights: {
      Qualifications: [
        "JavaScript, (React OR Angular OR Vue), Node, HTML, CSSS, API",
      ],
      Responsibilities: [
        "Starting 6/5, you will be working in an agile team to help develop a new set of web applications for their own system and sub vendors",
        "This role is hybrid and you will be required to go in to the office 3 days p/w",
      ],
      Benefits: [
        "6-month contract (likely extension)",
        "W2 - $70 - $75 p/h",
        "C2C - $80 - $90 p/h",
      ],
    },
  },
  {
    employer_name: "Spurs Sports & Entertainment",
    employer_logo:
      "https://firstteeaustin.org/wp-content/uploads/sites/64/2016/11/spurs-sports-and-entertainment-LOGO.jpg",
    employer_website: "http://www.spurs.com",
    employer_company_type: "Consulting",
    job_id: "UzcMt4Nb4qkAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Senior Web Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/senior-web-developer-at-spurs-sports-entertainment-3617222882",
    job_description:
      "Overview We are looking for Senior Web Developer to join our family! At Spurs Sports & Entertainment (SS&E), we work in service of something bigger than ourselves, it’s so much more than the game or concert itself. It takes all members of our Spurs Family to harness the power of sports and entertainment to build moments that endure, memories that excite, and connections that strengthen our community. This position will support and manage both app and website development across the Spurs Sports & Entertainment portfolio. You will develop user-focused products, develop meaningful metrics and tracking them over time to establish a program of continuous innovation and improvement. In addition to the above, this position will also be responsible for the development and maintenance of all websites in SS&E’s portfolio. Candidates should be flexible to modern development practices, embrace emerging standards and technology while advocating for the best methodologies. Overview -NOTE: This position is not responsible for social media administration. This position focuses on front end web and mobile app development and requires coding/programming skills necessary to build and solve assets both from scratch and from within multiple CMS environments. Does this sound like a fit? If so, we want to hear from you! In every position, each employee is expected to: Demonstrate Alignment with SS&E’s Core Values and Mission, Collaborate with Internal/External Family Members and Demonstrate Ongoing Development. Responsibilities • Write clean, reusable, and accessible client-side component code for web applications. • Understand product requirement documentation/functional specifications and develop application based upon specifications • Collaborate with project partners to ensure all requirements are met • Interact regularly with users to capture feedback, listen to their issues and concerns, recommend solutions. • Apply knowledge of modern web development to build and maintain responsive web pages • Be responsible for quality assurance testing for all digital platforms • Provide technical and developmental mentorship to junior developers • Other duties as assigned Qualifications • 2-4 years’ experience developing responsive, web-based applications • 2+ years’ experience using version control - Git, GitHub, etc. • Experience with front-end development languages and markups (JavaScript, CSS, HTML, etc.) • Experience with UI CSS and/or JavaScript frameworks (Bootstrap, Materialize, Vue.JS, React, jQuery, etc.) • Familiarity and knowledge of API, JSON, XML, and other common data frameworks. • Experience working in content management systems • Ability to creatively problem solve, work independently and coordinate multiple tasks • Strong teamwork and interpersonal skills to handle acute and confidential situations and information Preferred Qualifications • Javascript framework experience a plus (Node.js, React.js, Next.js) • Previous experience in sports or event industries • Understanding of UX / UI / SEO principles EEO Statement • SS&E is an Equal Opportunity Employer* Nothing contained in this job description is intended to be a contract of employment, nor does any information contained herein represent a guarantee of employment for a specific duration. Your employment with SS&E is “at will”, which means that either you or SS&E may terminate the relationship at any time. We will ensure that individuals with disabilities are provided reasonable accommodation to participate in the job application or interview process, to perform essential job functions, and to receive other benefits and privileges of employment. Please contact us to request accommodation.",
    job_posted_at_datetime_utc: "2023-05-31T09:39:37.000Z",
    job_city: "San Antonio",
    job_state: "TX",
    job_country: "US",
    job_offer_expiration_datetime_utc: "2023-06-30T09:39:37.000Z",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_highlights: {
      Qualifications: [
        "This position focuses on front end web and mobile app development and requires coding/programming skills necessary to build and solve assets both from scratch and from within multiple CMS environments",
        "2-4 years’ experience developing responsive, web-based applications",
        "2+ years’ experience using version control - Git, GitHub, etc",
        "Experience with front-end development languages and markups (JavaScript, CSS, HTML, etc.)",
        "Experience with UI CSS and/or JavaScript },frameworks (Bootstrap, Materialize, Vue.JS, React, jQuery, etc.)",
        "Familiarity and knowledge of API, JSON, XML, and other common data frameworks",
        "Experience working in content management systems",
        "Ability to creatively problem solve, work independently and coordinate multiple tasks",
        "Strong teamwork and interpersonal skills to handle acute and confidential situations and information",
      ],
      Responsibilities: [
        "This position will support and manage both app and website development across the Spurs Sports & Entertainment portfolio",
        "You will develop user-focused products, develop meaningful metrics and tracking them over time to establish a program of continuous innovation and improvement",
        "In addition to the above, this position will also be responsible for the development and maintenance of all websites in SS&E’s portfolio",
        "Write clean, reusable, and accessible client-side component code for web applications",
        "Understand product requirement documentation/functional specifications and develop application based upon specifications",
        "Collaborate with project partners to ensure all requirements are met",
        "Interact regularly with users to capture feedback, listen to their issues and concerns, recommend solutions",
        "Apply knowledge of modern web development to build and maintain responsive web pages",
        "Be responsible for quality assurance testing for all digital platforms",
        "Provide technical and developmental mentorship to junior developers",
        "Other duties as assigned",
      ],
    },
  },
  {
    employer_name: "Archetype Permanent Solutions",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_id: "JviQ_0mnlXoAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Web developer",
    job_apply_link: "https://www.talent.com/view?id=d9389c3c7cd3",
    job_description:
      "Responsibilities : • Develop and maintain web applications using modern web technologies and programming languages • Work with cross-functional teams to understand business requirements and develop appropriate solutions • Write well-designed, testable, and efficient code using appropriate software development methodologies • Develop and maintain database schemas, queries, and stored procedures in SQL databases • Work with PLC logic and interface with web applications • Collaborate with front-end developers to integrate user-facing elements with server-side logic • Ensure the technical feasibility of UI / UX designs • Optimize web applications for maximum speed and scalability • Troubleshoot and debug web applications as necessary • Stay up-to-date with emerging trends and technologies in web development Requirements : • Bachelor's degree in Computer Science, Information Technology or related field • Proven experience in full stack web development with a focus on server-side technologies • Strong experience with Windows Server, SQL databases, and PLC logic • Proficient understanding of web markup, including HTML5, CSS3, and JavaScript frameworks (e.g. AngularJS, ReactJS) • Experience with web development frameworks such as ASP.NET , Node.js, Ruby on Rails, or Django • Knowledge of at least one server-side programming language such as C#, Java, or Python • Experience with version control systems such as Git • Strong analytical and problem-solving skills • Excellent communication and collaboration skills • Ability to work independently as well as in a team-oriented environment • Bilingual English and Korean If you are an experienced Full Stack Web Developer with a passion for developing cutting-edge web applications and a desire to work with a dynamic team, please apply for this position. We offer a competitive salary, benefits package, and opportunities for professional growth and advancement. Powered by JazzHR Last updated : 2023-06-01",
    job_posted_at_datetime_utc: "2023-06-01T00:00:00.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_offer_expiration_datetime_utc: "2023-09-02T00:00:00.000Z",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science, Information Technology or related field",
        "Proven experience in full stack web development with a focus on server-side technologies",
        "Strong experience with Windows Server, SQL databases, and PLC logic",
        "Proficient understanding of web markup, including HTML5, CSS3, and JavaScript frameworks (e.g AngularJS, ReactJS)",
        "Experience with web development frameworks such as ASP",
        "Knowledge of at least one server-side programming language such as C#, Java, or Python",
        "Experience with version control systems such as Git",
        "Strong analytical and problem-solving skills",
        "Excellent communication and collaboration skills",
        "Ability to work independently as well as in a },team-oriented environment",
        "Bilingual English and Korean",
      ],
      Responsibilities: [
        "Develop and maintain web applications using modern web technologies and programming languages",
        "Work with cross-functional teams to understand business requirements and develop appropriate solutions",
        "Write well-designed, testable, and efficient code using appropriate software development methodologies",
        "Develop and maintain database schemas, queries, and stored procedures in SQL databases",
        "Work with PLC logic and interface with web applications",
        "Collaborate with front-end developers to integrate user-facing elements with server-side logic",
        "Ensure the technical feasibility of UI / UX designs",
        "Optimize web applications for maximum speed and scalability",
        "Troubleshoot and debug web applications as necessary",
        "Stay up-to-date with emerging trends and technologies in web development",
      ],
      Benefits: [
        "We offer a competitive salary, benefits package, and opportunities for professional growth and advancement",
      ],
    },
  },
  {
    employer_name: "NextAfter",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?,q=tbn:ANd9GcT3LtpFk_Qn5msyHfLis8HxKBBhhxla_ZNtS7bV&s=0",
    employer_website: null,
    employer_company_type: null,
    job_id: "DCi-37AXFUgAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Front End Web Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/front-end-web-developer-at-nextafter-3621796979",
    job_description:
      "At NextAfter, web developers are critical in allowing our nonprofit clients to escape the shackles of poorly designed software. Out-of-the-box software solutions rarely allow nonprofits the flexibility necessary to track every donor action or to make design tweaks to improve donor conversion. That is where you come in. In this role, you will be charged with helping organizations make websites do things they were never designed to do. You’ll apply your HTML, Javascript, and CSS skills toward crafting unique solutions to solve complex problems across a variety of different web platforms. Because NextAfter works solely with nonprofits to help them raise money and awareness for their causes, it’s also essential that every member on our team desires to positively impact the world around them and cares about the people they’re serving alongside and those at the organizations we help. The Front End Web Developer supports NextAfter’s efforts to discover what drives donors to give through setting up A/B experiments and optimizing the tracking of various advertising efforts. Essential Duties and Responsibilities include the following. Other duties may be assigned. • Setting up A/B experiments utilizing VWO, Optimizely, and similiar platforms. This will involve writing Javascript, HTML, and CSS to override existing page layout and design. • Implementing enhanced tracking to monitor the fundraising and marketing efforts. This is normally done with platforms such as Google Tag Manager, Google Analytics, Facebook, Google Ads, and other advertising platforms. • Configuring marketing software such as Mailchimp, Hubspot, and similar tools to serve the needs of the nonprofit clients that we work with. This involves setting up templates, implementing tracking, and making configuration changes based upon requirements. • Working with client service specialists to devise strategies and tactics that improve our clients’ performance. Qualifications and Skills: • Advanced knowledge of Javascript (ability to code without relying on outside libraries such as Vue.js, jQuery, React.js, etc.) • Experience with HTML and CSS to craft web pages • Knowledge of marketing platforms such as Hubspot, MailChimp, and Pardot • Experience implementing digital analytics platforms such as Google Analytics and Facebook • Knowledge of A/B testing and the associated platforms such as VWO Education and Experience • Bachelor’s degree (or comparable experience in a similar role) • Training in web development either from a Bachelor’s degree or coding bootcamp",
    job_posted_at_datetime_utc: "2023-05-31T21:36:47.000Z",
    job_city: "Plano",
    job_state: "TX",
    job_country: "US",
    job_offer_expiration_datetime_utc: "2023-06-30T21:36:47.000Z",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_highlights: {
      Qualifications: [
        "Advanced knowledge of Javascript (ability to code without relying on outside libraries such as Vue.js, jQuery, React.js, etc.)",
        "Experience with HTML and CSS to craft web pages",
        "Knowledge of marketing platforms such as Hubspot, MailChimp, and Pardot",
        "Experience implementing digital analytics platforms such as Google Analytics and Facebook",
        "Knowledge of A/B testing and the associated platforms such as VWO",
        "Bachelor’s degree (or comparable experience in a similar role)",
        "Training in web development either from a Bachelor’s degree or coding bootcamp",
      ],
      Responsibilities: [
        "In this role, you will be charged with helping organizations make websites do things they were never designed to do",
        "You’ll apply your HTML, Javascript, and CSS skills toward crafting unique solutions to solve complex problems across a variety of different web platforms",
        "Setting up A/B experiments utilizing VWO, Optimizely, and similiar platforms",
        "This will involve writing Javascript, HTML, and CSS to override existing page layout and design",
        "Implementing enhanced tracking to monitor the fundraising and marketing efforts",
        "This is normally done with platforms such as Google Tag Manager, Google Analytics, Facebook, Google Ads, and other advertising platforms",
        "Configuring marketing software such as Mailchimp, Hubspot, and similar tools to serve the needs of the nonprofit clients that we work with",
        "This involves setting up templates, implementing tracking, and making configuration changes based upon requirements",
        "Working with client service specialists to devise strategies and tactics that improve our clients’ performance",
      ],
    },
  },
  {
    employer_name: "PCS Software",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_id: "RmMWVIxJKacAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Senior React Front-End Web Developer",
    job_apply_link:
      "https://www.learn4good.com/jobs/sugar-land/texas/software_development/2355985733/e/",
    job_description:
      "Senior React Front-End Web Developer Targeted Start Date: ASAP Location: on site in the PCS Houston Regional Office (this is not a remote role, but has a flexible work schedule) Immediate Supervisor: Director of Development Company Background PCS Software, Inc. is an AI platform for the transportation logistics market space providing the trucking industry's most effective transportation management platform (TMP) to improve fleet management and delivery systems and increase profits for our customers. Through innovation and invention, our software individualizes work routines, consolidates workflows, and streamlines management controls to improve accountability, transparency, and eliminate costly and redundant manual processes. Trucking companies and freight brokers trust PCS to optimize their dispatch, accounting, and fleet operations. TL, LTL, Intermodal, and freight brokerage services use our TMP to automate operations, easily access information, and reduce inefficiencies to maximize sales and revenue. Founded in 1997 and headquartered in Houston, Texas, with regional offices now located across North America, PCS Software is the leading developer of hosted software solutions designed specifically for the ground transportation industry. Job Description: Senior React Front-End Web Developer Role and Responsibilities Technical resource responsible for front-end development using web technologies which include, but are not limited to: HTML, CSS, JavaScript, and React/Redux. Building reusable components and front-end libraries for future use Responsible for translating designs and wireframes into high quality code Optimizing components for maximum performance across a vast array of web-capable devices and browse Ensure technical feasibility of UI/UX designs Champion requirement evaluation and impact analysis Participate in code reviews and share best practices periodically Continuous integration with Jenkins CI Participate in full SDLC, including meetings, interactive development, estimations, and design sessions Work in a collaborative environment with other developers and QA team members, product designers, product managers, and off-site 3rd party vendor team members Deliver code solutions built for performance, availability, and scalability optimizing applications for maximum speed and scalability Code and unit test functionality and/or integrations between systems Support and troubleshoot issues (process and system), identify the root cause, and proactively implement sustainable corrective actions Building reusable code and libraries for future use Stay current with the fast-changing landscape of browser-based application development Monitor the development of, evaluate, and recommend new technologies/approaches to the development pipeline Mentor other developers (and interns occasionally) to increase the overall skill level of the team and quality of team output Review code produced by other developers for acceptance into the repository Develop a thorough understanding of policies, procedures, and safety rules Duties may change; Team Members may be required to perform other duties as assigned Work Experience Required 3+ years of experience developing and deploying large-scale websites and website content or demonstrated skill level in previous positions 3+ years of experience Design and developing application in React. Js/Redux. 3+ years of experience Design and developing application in JavaScript technologies. Experience with a 500+ million revenue e-commerce retailer preferred Proven understanding of design patterns, reference architectures, industry standards, broad technical knowledge, and architectural principles is necessary Demonstrated ability to provide and recommend innovative ideas with the skill to align projects with enterprise strategy is needed Ability to work efficiently and accurately under pressure, meet deadlines, present a professional demeanor, and work well independently is essential Ability to estimate financial impact of technical architecture alternatives and apply multiple technical solutions to business problems is vital Technical Knowledge and Skills Required Experience building responsive websites using React. JS and Node. JS Experience in client-side scripting, libraries, and structures which include HTML5, CSS3, JavaScript, XML, and JSON Understanding of Content Stack and Content Stack integration with React. Js Thorough understanding of React. Js and its core principles Experience with popular React.js workflows (such as Flux or Redux) Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model Experience with common front-end development tools such as Babel, Webpack, NPM, etc. Experience writing unit tests for Java Script Experience with Responsive Web Design Knowledge of modern authorization mechanisms, such as JSON Web Token Familiarity with modern front-end build pipelines and tools Ability to understand business requirements and translate them into technical requirements A knack for…",
    job_posted_at_datetime_utc: "2023-05-30T00:00:00.000Z",
    job_city: "Sugar Land",
    job_state: "TX",
    job_country: "US",
    job_offer_expiration_datetime_utc: null,
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_highlights: {
      Qualifications: [
        "3+ years of experience developing and deploying large-scale websites and website content or demonstrated skill level in previous positions",
        "3+ years of experience Design and developing application in JavaScript technologies",
        "Proven understanding of design patterns, reference architectures, industry standards, broad technical knowledge, and architectural principles is necessary",
        "Demonstrated ability to provide and recommend innovative ideas with the skill to align projects with enterprise strategy is needed",
        "Ability to work efficiently and accurately under pressure, meet deadlines, present a professional demeanor, and work well independently is essential",
        "Ability to estimate financial impact of technical architecture alternatives and apply multiple technical solutions to business problems is vital",
        "Technical Knowledge and Skills Required Experience building responsive websites using React",
        "Experience in client-side scripting, libraries, and structures which include HTML5, CSS3, JavaScript, XML, and JSON",
        "Understanding of Content Stack and Content Stack integration with React",
        "Thorough understanding of React",
        "Js and its core principles",
        "Experience with popular React.js workflows (such as Flux or Redux)",
        "Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model",
        "Experience with common front-end development tools such as Babel, Webpack, NPM, etc",
        "Experience writing unit tests for Java Script",
        "Experience with Responsive Web Design",
        "Knowledge of modern authorization mechanisms, such as JSON Web Token",
        "Familiarity with modern front-end build pipelines and tools",
        "Ability to understand business requirements and translate them into technical requirements",
      ],
      Responsibilities: [
        "Trucking companies and freight brokers trust PCS to optimize their dispatch, accounting, and fleet operations",
        "Responsibilities Technical resource responsible for front-end development using web technologies which include, but are not limited to: HTML, CSS, JavaScript, and React/Redux",
        "Building reusable components and front-end libraries for future use",
        "Responsible for translating designs and wireframes into high quality code",
        "Optimizing components for maximum performance across a vast array of web-capable devices and browse",
        "Ensure technical feasibility of UI/UX designs",
        "Champion requirement evaluation and impact analysis",
        "Participate in code reviews and share best practices periodically",
        "Continuous integration with Jenkins CI",
        "Participate in full SDLC, including meetings, interactive development, estimations, and design sessions",
        "Work in a collaborative environment with other developers and QA team members, product designers, product managers, and off-site 3rd party vendor team members",
        "Deliver code solutions built for performance, availability, and scalability optimizing applications for maximum speed and scalability",
        "Code and unit test functionality and/or integrations between systems",
        "Support and troubleshoot issues (process and system), identify the root cause, and proactively implement sustainable corrective actions",
        "Stay current with the fast-changing landscape of browser-based application development",
        "Monitor the development of, evaluate, and recommend new technologies/approaches to the development pipeline",
        "Mentor other developers (and interns occasionally) to increase the overall skill level of the team and quality of team output",
        "Review code produced by other developers for acceptance into the repository",
        "Develop a thorough understanding of policies, procedures, and safety rules",
        "Team Members may be required to perform other duties as assigned",
      ],
    },
  },
  {
    employer_name: "AT&T",
    employer_logo:
      "https://www.att.com/shopcms/media/att/2014/global/social-logo/logo-att-color-trans-200x200.png",
    employer_website: "https://www.att.com",
    employer_company_type: "Information",
    job_id: "1lr1uWOWY3MAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Front End Developer",
    job_apply_link:
      "https://www.att.jobs/job/dallas/front-end-developer/117/49435018000",
    job_description:
      "About the Company Join AT&T and reimagine the communications and technologies that connect the world. Our Consumer Technology eXperience team is delivering innovative and reliable technology solutions to power differentiated, simplified customer experiences. Bring your bold ideas and fearless risk-taking to redefine connectivity and transform how the world shares stories and experiences that matter. When you step into a career with AT&T, you won’t just imagine the future-you’ll create it. About the Team AT&T Digital Platform Product team is looking for a Professional-Software Engineer (FE heavy) who is passionate about the eCommerce industry and has analytical and multi-task abilities to thrive in a fast-paced environment. As a Lead Engineer, you will be responsible for the design and development of various initiatives for AT&T’s customer and employee digital experience across our consumer distribution channels. You will lead the software product development life cycle from inception to production launch and post-production support. You must possess strong technical background to ensure you are designing modular & scalable web components, you must have experience leading large cross-organizational software development projects and have a well-rounded technical background in current web and micro-service technologies. About the Job Position Overview AT&T Digital Platform Product team is looking for a Professional-Software Engineer (FE heavy) who is passionate about the eCommerce industry and has analytical and multi-task abilities to thrive in a fast-paced environment. As a Lead Engineer, you will be responsible for the design and development of various initiatives for AT&T’s customer and employee digital experience across our consumer distribution channels. You will lead the software product development life cycle from inception to production launch and post-production support. You must possess strong technical background to ensure you are designing modular & scalable web components, you must have experience leading large cross-organizational software development projects and have a well-rounded technical background in current web and micro-service technologies. Responsibilities and Day-to-Day View Responsibilities • Hands-on Design and development of cross-functional, multi-platform application systems • Track record of projects completed on time – you are a flawless executor, not a procrastinator. • You find satisfaction in a job well done and want to solve head-scratching challenges. • Experience with all phases of the software development life cycle, best practices and Agile Software Development. • Work with Leads, Engineers, Architects, Product Managers, and Business stakeholders to identify technical and functional needs of systems based on priority. • Writing great quality code with a relentless passion for automated testing and validation. • Enforce company policies in the areas of development methodology, architecture, security, change and configuration management and compliance. • Perform complex engineering activities for web performance tuning, monitoring, deployment and production support. Qualifications Required Qualifications • 2+ years related experience • 2+ years in web markup, including REACT, HTML5, CSS3 and javascript • 2+ years of experience with client-side scripting and javascript frameworks such as jquery and React • 2+ years of experience in server-side rendering using NextJs • Proficient understanding of javascript pre-processing and packaging frameworks such as babel and webpack • Good understanding of Java, Nodejs, microservice and some full stack experience. While you’ll be spending most of your time in the V of MVC, we’ll occasionally need help further back in the stack • Good understanding of SEO principles including web analytics and ensuring that application will adhere to them • Excellent communication skills and experience in collaborative environments • The desire to be continually learning about emerging technologies/industry trends Preferred Qualifications • Preferred Bachelors of Science degree in Computer Engineering, Computer Science, Applied Science, Electrical Engineering, or Math; Developer nanodegree • 2+ years of understanding of CSS pre-processing platforms, such as LESS and SASS • 2+ years of experience in build and CICD technologies: GitHub, Maven, Jenkins, Sonar • 2+ years of experience in Unit and Function testing using Junit, Spock, Mockito/JMock, Selenium, Cucumber, SoapUI or Postman • Experience working within Agile/Scrum/Kanban development team • Familiarity with HTML5, JavaScript frameworks, and CSS3 • Excellent written and verbal communication skills with demonstrated ability to present complex technical information in a clear manner to peers, developers, and leaders Technical Skills ReactJs, NodeJs, Html, Java, Nodejs, microservices, cloud, REST services, NoSql technologies (Cassandra/MongoDb), knowledge of Redis/Hazelcast, Git, Jira, Jenkins Our Professional-Software Engineers earn between $116,700 - $175,100. Not to mention all the other amazing rewards that working at AT&T offers. Individual starting salary within this range may depend on geography, experience, expertise, and education/training. Joining our team comes with amazing perks and benefits: · Medical/Dental/Vision coverage · 401(k) plan · Tuition reimbursement program · Paid Time Off and Holidays (based on date of hire, at least 23 days of vacation each year and 9 company-designated holidays) · Paid Parental Leave · Paid Caregiver Leave · Additional sick leave beyond what state and local law require may be available but is unprotected · Adoption Reimbursement · Disability Benefits (short term and long term) · Life and Accidental Death Insurance · Supplemental benefit programs: critical illness/accident hospital indemnity/group legal · Employee Assistance Programs (EAP) · Extensive employee wellness programs · Employee discounts up to 50% off on eligible AT&T mobility plans and accessories, AT&T internet (and fiber where available) and AT&T phone AT&T is leading the way to the future – for customers, businesses and the industry. We're developing new technologies to make it easier for our customers to stay connected to their world. Together, we’ve built a premier integrated communications and entertainment company and an amazing place to work and grow. Team up with industry innovators every time you walk into work, creating the world you always imagined. Ready to #transformdigital with us? Apply now!",
    job_posted_at_datetime_utc: "2023-05-27T00:00:00.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_offer_expiration_datetime_utc: null,
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_highlights: {
      Qualifications: [
        "You must possess strong technical background to ensure you are designing modular & scalable web components, you must have experience leading large cross-organizational software development projects and have a well-rounded technical background in current web and micro-service technologies",
        "2+ years related experience",
        "2+ years in web markup, including REACT, HTML5, CSS3 and javascript",
        "2+ years of experience with client-side scripting and javascript frameworks such as jquery and React",
        "2+ years of experience in server-side rendering using NextJs",
        "Proficient understanding of javascript pre-processing and packaging frameworks such as babel and webpack",
        "Good understanding of Java, Nodejs, microservice and some full stack experience",
        "Good understanding of SEO principles including web analytics and ensuring that application will adhere to them",
        "Excellent communication skills and experience in collaborative environments",
        "The desire to be continually learning about emerging technologies/industry trends",
        "ReactJs, NodeJs, Html, Java, Nodejs, microservices, cloud, REST services, NoSql technologies (Cassandra/MongoDb), knowledge of Redis/Hazelcast, Git, Jira, Jenkins",
      ],
      Responsibilities: [
        "As a Lead Engineer, you will be responsible for the design and development of various initiatives for AT&T’s customer and employee digital experience across our consumer distribution channels",
        "You will lead the software product development life cycle from inception to production launch and post-production support",
        "Hands-on Design and development of cross-functional, multi-platform application systems",
        "Track record of projects completed on time – you are a flawless executor, not a procrastinator",
        "You find satisfaction in a job well done and want to solve head-scratching challenges",
        "Experience with all phases of the software development life cycle, best practices and Agile Software Development",
        "Work with Leads, Engineers, Architects, Product Managers, and Business stakeholders to identify technical and functional needs of systems based on priority",
        "Writing great quality code with a relentless passion for automated testing and validation",
        "Enforce company policies in the areas of development methodology, architecture, security, change and configuration management and compliance",
        "Perform complex engineering activities for web performance tuning, monitoring, deployment and production support",
      ],
      Benefits: [
        "Our Professional-Software Engineers earn between $116,700 - $175,100",
        "Individual starting salary within this range may depend on geography, experience, expertise, and education/training",
        "Medical/Dental/Vision coverage",
        "401(k) plan",
        "Tuition reimbursement program",
        "Paid Time Off and Holidays (based on date of hire, at least 23 days of vacation each year and 9 company-designated holidays)",
        "Paid Parental Leave",
        "Paid Caregiver Leave",
        "Additional sick leave beyond what state and local law require may be available but is unprotected",
        "Adoption Reimbursement",
        "Disability Benefits (short term and long term)",
        "Life and Accidental Death Insurance",
        "Supplemental benefit programs: critical illness/accident hospital indemnity/group legal",
        "Employee Assistance Programs (EAP)",
        "Extensive employee wellness programs",
        "Employee discounts up to 50% off on eligible AT&T mobility plans and accessories, AT&T internet (and fiber where available) and AT&T phone",
      ],
    },
  },
  {
    employer_name: "Connecttel, Inc",
    employer_logo:
      "https://logoimagesv2.id-visitors.com/0/b/5/4/4/f/0b544fc53a4c40dfa112c91442f219d6.png",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Dice",
    job_id: "uSveAal9k1IAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Front-End Developer (JavaScript, HTML, CSS)",
    job_apply_link:
      "https://www.dice.com/job-detail/35181ab6-1420-4e02-896c-2c506f1cb5e2",
    job_description:
      "Front-End Developer Austin, TX (Relocation and immigration visa sponsorship is not currently available.) Full time Are you an amazing developer ready to work in a collaborative team? Do you want to have your voice heard in a small but stable and profitable company? Do you enjoy thinking creatively and constantly learning? Most importantly, are you a dog lover? Then you might be just who we're looking for! Hiring developers to help us create new and exciting web-based user interfaces. What you'll be doing: Engineering lightweight UI components that scale well over time and meet modern web standards Transforming wireframes from conception to reality while collaborating with a team Building software used by some of the largest financial institutions in the world Continually improving our UI code base by contributing to code reviews and routine maintenance You: Have a bachelor's degree in computer science or a related field Love working in visual mediums and UI/UX Have experience with object-oriented programming Are a self-starter who takes initiative and helps drive the product design Feel comfortable working in a non-structured, agile development environment with short release cycles Are interested in financial technology Must love dogs Optional but helpful skills: 3 years of experience Familiarity with JavaScript, HTML, CSS Familiarity with any JavaScript Framework Familiarity with a version control system Experience interacting with a web service API Experience with website design What we offer: A highly competitive salary Company-paid family health, vision, and dental insurance 401K with employer matching A fun and relaxed environment in a small but profitable and stable company Opportunity to learn about the financial services industry in the US, UK, Ireland, Canada, Europe and Asia Opportunity for international travel if desired",
    job_posted_at_datetime_utc: "2023-02-06T09:18:41.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_offer_expiration_datetime_utc: "2023-12-01T09:20:01.000Z",
    job_highlights: {
      Qualifications: [
        "You: Have a bachelor's degree in computer science or a related field",
        "Love working in visual mediums and UI/UX",
        "Have experience with object-oriented programming",
        "Are a self-starter who takes initiative and helps drive the product design",
        "Feel comfortable working in a non-structured, agile development environment with short release cycles",
        "Are interested in financial technology",
        "3 years of experience",
        "Familiarity with JavaScript, HTML, CSS",
        "Familiarity with any JavaScript Framework",
        "Familiarity with a version control system",
        "Experience interacting with a web service API",
        "Experience with website design",
      ],
      Responsibilities: [
        "Engineering lightweight UI components that scale well over time and meet modern web standards",
        "Transforming wireframes from conception to reality while collaborating with a team",
        "Building software used by some of the largest financial institutions in the world",
        "Continually improving our UI code base by contributing to code reviews and routine maintenance",
      ],
    },
  },
];
